### ISSUE TITLE
Cannot use HLS 2.5.0.0

### ISSUE THREAD

**Issue by felixlinker** [haskell/vscode-haskell#1047]
### Your environment

Which OS do you use:

MacOS (M2)

### Steps to reproduce

1. Install HLS 2.5.0.0 but not 2.6.0.0 using GHCUP
2. Clone https://github.com/tamarin-prover/tamarin-prover
3. Open the cloned repository in vscode

### Expected behaviour

The extension should launch HLS and work as expected

### Actual behaviour

The extension prompts me to install HLS 2.6.0.0 and raises and error if I refuse to install

### Include debug information

<details>
<summary>
Debug output:
</summary>

(I did not include these logs because HLS 2.5.0.0 works as expected when launched from the console. Thus, the log is huge.)

</details>

<details>
<summary>
Extension log:
</summary>

```
2024-02-13 09:50:27.8880000 [client] DEBUG Environment variables:
2024-02-13 09:50:27.8880000 [client] DEBUG   PATH: /Users/felixlinker/.nvm/versions/node/v21.1.0/bin:/Users/felixlinker/.cabal/bin:/Users/felixlinker/.ghcup/bin:/Users/felixlinker/bin/scripts:/Users/felixlinker/bin/maude:/Users/felixlinker/git/diff-so-fancy:/Users/felixlinker/Library/Python/3.12/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/usr/local/go/bin
2024-02-13 09:50:27.8880000 [client] INFO Finding haskell-language-server
2024-02-13 09:50:27.8880000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:27.8910000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:27.8910000 [client] INFO Executing 'ghcup --no-verbose upgrade' in cwd '/'
2024-02-13 09:50:27.9980000 [client] DEBUG Execution of 'ghcup --no-verbose upgrade' terminated with code 0
2024-02-13 09:50:27.9980000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:28.0000000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:28.0000000 [client] INFO Executing 'ghcup --no-verbose list -t hls -c installed -r' in cwd '/'
2024-02-13 09:50:28.0560000 [client] DEBUG Execution of 'ghcup --no-verbose list -t hls -c installed -r' terminated with code 0
2024-02-13 09:50:28.0560000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:28.0580000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:28.0580000 [client] INFO Executing 'ghcup --no-verbose list -t cabal -c installed -r' in cwd '/'
2024-02-13 09:50:28.1190000 [client] DEBUG Execution of 'ghcup --no-verbose list -t cabal -c installed -r' terminated with code 0
2024-02-13 09:50:28.1200000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:28.1210000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:28.1210000 [client] INFO Executing 'ghcup --no-verbose list -t stack -c installed -r' in cwd '/'
2024-02-13 09:50:28.1790000 [client] DEBUG Execution of 'ghcup --no-verbose list -t stack -c installed -r' terminated with code 0
2024-02-13 09:50:28.1810000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:28.1820000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:28.1830000 [client] INFO Executing 'ghcup --no-verbose whereis hls 2.5.0.0' in cwd '/'
2024-02-13 09:50:28.2000000 [client] DEBUG Execution of 'ghcup --no-verbose whereis hls 2.5.0.0' terminated with code 0
2024-02-13 09:50:28.2000000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:28.2020000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:28.2020000 [client] INFO Executing 'ghcup --no-verbose whereis cabal 3.10.2.1' in cwd '/'
2024-02-13 09:50:28.2220000 [client] DEBUG Execution of 'ghcup --no-verbose whereis cabal 3.10.2.1' terminated with code 0
2024-02-13 09:50:28.2220000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:28.2240000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:28.2240000 [client] INFO Executing 'ghcup --no-verbose whereis stack 2.13.1' in cwd '/'
2024-02-13 09:50:28.2440000 [client] DEBUG Execution of 'ghcup --no-verbose whereis stack 2.13.1' terminated with code 0
2024-02-13 09:50:28.2460000 [client] INFO Executing 'ghc --numeric-version' in cwd '/'
2024-02-13 09:50:28.2910000 [client] DEBUG Execution of 'ghc --numeric-version' terminated with code 0
2024-02-13 09:50:28.2910000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:28.2930000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:28.2940000 [client] INFO Executing 'ghcup --no-verbose run --hls 2.5.0.0 --cabal 3.10.2.1 --stack 2.13.1 --install' in cwd '/'
2024-02-13 09:50:28.3630000 [client] DEBUG Execution of 'ghcup --no-verbose run --hls 2.5.0.0 --cabal 3.10.2.1 --stack 2.13.1 --install' terminated with code 0
2024-02-13 09:50:28.3630000 [client] INFO Working out the project GHC version. This might take a while...
2024-02-13 09:50:28.3630000 [client] INFO Executing 'haskell-language-server-wrapper --project-ghc-version' in cwd '/Users/felixlinker/git/tamarin-prover'
2024-02-13 09:50:29.1440000 [client] DEBUG Execution of 'haskell-language-server-wrapper --project-ghc-version' terminated with code 0
2024-02-13 09:50:29.1440000 [client] INFO The GHC version for the project or file: 9.2.8
2024-02-13 09:50:29.3300000 [client] INFO Platform constants: Darwin, A_ARM64
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.4.0 compatible with GHC Versions: 8.10.7
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.5.0 compatible with GHC Versions: 8.10.7
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.5.1 compatible with GHC Versions: 8.10.7
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.6.0.0 compatible with GHC Versions: 8.10.7
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.6.1.0 compatible with GHC Versions: 8.10.7
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.7.0.0 compatible with GHC Versions: 8.10.7,9.0.2,9.2.1,9.2.2
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.8.0.0 compatible with GHC Versions: 8.10.7,9.0.2,9.2.3,9.2.4,9.4.1,9.4.2
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.9.0.0 compatible with GHC Versions: 8.10.7,9.0.2,9.2.5,9.4.3,9.4.4
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.9.1.0 compatible with GHC Versions: 8.10.7,9.2.5,9.2.6,9.4.4
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 1.10.0.0 compatible with GHC Versions: 8.10.7,9.2.7,9.4.4,9.6.1
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.0.0.0 compatible with GHC Versions: 8.10.7,9.2.7,9.4.5,9.6.1
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.0.0.1 compatible with GHC Versions: 8.10.7,9.2.7,9.2.8,9.4.5,9.6.2
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.1.0.0 compatible with GHC Versions: 8.10.7,9.2.8,9.4.5,9.4.6,9.6.2
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.2.0.0 compatible with GHC Versions: 8.10.7,9.2.8,9.4.5,9.4.6,9.4.7,9.6.2
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.3.0.0 compatible with GHC Versions: 9.2.8,9.4.7,9.6.2,9.6.3
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.4.0.0 compatible with GHC Versions: 9.2.8,9.4.7,9.6.3,9.8.1
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.5.0.0 compatible with GHC Versions: 9.2.8,9.4.8,9.6.3,9.8.1
2024-02-13 09:50:29.3300000 [client] DEBUG HLS 2.6.0.0 compatible with GHC Versions: 9.2.8,9.4.8,9.6.4,9.8.1
2024-02-13 09:50:29.3310000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:29.3350000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:29.3360000 [client] INFO Executing 'ghcup --no-verbose list -t hls -c installed -r' in cwd '/'
2024-02-13 09:50:29.4100000 [client] DEBUG Execution of 'ghcup --no-verbose list -t hls -c installed -r' terminated with code 0
2024-02-13 09:50:29.4100000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:29.4120000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:29.4130000 [client] INFO Executing 'ghcup --no-verbose whereis bindir' in cwd '/'
2024-02-13 09:50:29.4330000 [client] DEBUG Execution of 'ghcup --no-verbose whereis bindir' terminated with code 0
2024-02-13 09:50:29.4340000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:29.4360000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:29.4360000 [client] INFO Executing 'ghcup --no-verbose whereis hls 2.6.0.0' in cwd '/'
2024-02-13 09:50:29.4540000 [client] DEBUG Execution of 'ghcup --no-verbose whereis hls 2.6.0.0' terminated with code 30
2024-02-13 09:50:29.4540000 [client] ERROR Error executing 'ghcup --no-verbose whereis hls 2.6.0.0' with error code 30
2024-02-13 09:50:29.4540000 [client] ERROR stderr: [1m[ Error ][0m []8;;https://errors.haskell.org/messages/GHCup-00130\GHCup-00130]8;;\] The version 2.6.0.0 of the tool hls is not installed.

2024-02-13 09:50:29.4540000 [client] INFO Checking for ghcup installation
2024-02-13 09:50:29.4560000 [client] INFO found ghcup at ghcup
2024-02-13 09:50:29.4560000 [client] INFO Executing 'ghcup --no-verbose whereis ghc 9.2.8' in cwd '/'
2024-02-13 09:50:29.4770000 [client] DEBUG Execution of 'ghcup --no-verbose whereis ghc 9.2.8' terminated with code 0
2024-02-13 09:50:34.1110000 [client] ERROR Error: Project requires HLS but it isn't installed
	at /Users/felixlinker/.vscode/extensions/haskell.haskell-2.4.3/dist/extension.js:1:60932
	at Array.forEach (<anonymous>)
	at /Users/felixlinker/.vscode/extensions/haskell.haskell-2.4.3/dist/extension.js:1:60878
	at Generator.next (<anonymous>)
	at s (/Users/felixlinker/.vscode/extensions/haskell.haskell-2.4.3/dist/extension.js:1:47699)
```

</details>

### Note

Obviously, I could avoid this issue by installing HLS 2.6.0.0. This, however, does not work for me because HLS 2.6.0.0 keeps running into dependency issues. These dependency issues might be related to: https://github.com/haskell/haskell-language-server/issues/3472 Thus, I would like to use HLS 2.5.0.0, and by the logs, you can see that it is detected and should work.

Let me also note that this issue only started appearing recently. Until 1-2 weeks ago, I could use HLS 2.5.0.0 just fine.

**Comment by felixlinker** [comment]
Reading the HLS issues referenced above again, I ran `stack purge && stack build` and now HLS 2.6.0.0 seems to work. I.e., issue is not as pressing anymore.

I would still appreciate if I could use HLS 2.5.0.0, though, because I already could get HLS 2.6.0.0 to work in the past, but I keep running into issues with that version.
