### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by maguldemond** [haskell/vscode-haskell#434]
- Issue Type: `Bug`
- Extension Name: `haskell`
- Extension Version: `1.6.0`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.59.0`

I'm trying to run the Haskell extension on VS Code on MacOS. I have tried restarting VS Code, but when I try to right click to get a definition, it starts "Processing". And it hangs there like that for hours. (see screen shot)

I'm trying to work on IOHK Plutus code. When setting up the Plutus repos on a linux Docker container, it took several hours to build. 

I also noticed in the VS Code list of running extensions, that the Haskell extension has 1 uncaught error. (see screenshot) The Extension Host Log has this error in it:

[2021-08-11 14:49:08.226] [exthost] [error] TypeError: Cannot read property 'slice' of null
	at InteroLocationDecoder.extractRange (/Users/marcelg/.vscode/extensions/ucl.haskelly-0.5.5/out/src/Providers/InteroLocationDecoder.js:24:13)
	at InteroLocationDecoder.buildLocation (/Users/marcelg/.vscode/extensions/ucl.haskelly-0.5.5/out/src/Providers/InteroLocationDecoder.js:11:28)
	at InteroLocationDecoder.decode (/Users/marcelg/.vscode/extensions/ucl.haskelly-0.5.5/out/src/Providers/InteroLocationDecoder.js:6:21)
	at HaskellDefinitionProvider.<anonymous> (/Users/marcelg/.vscode/extensions/ucl.haskelly-0.5.5/out/src/Providers/Definition/index.js:24:47)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/marcelg/.vscode/extensions/ucl.haskelly-0.5.5/out/src/Providers/Definition/index.js:4:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

<img width="569" alt="Screen Shot 2021-08-11 at 3 31 35 PM" src="https://user-images.githubusercontent.com/2962686/128996767-dbee61c2-c9fe-4487-9f0e-e728a805b05d.png">
<img width="516" alt="Screen Shot 2021-08-11 at 3 31 23 PM" src="https://user-images.githubusercontent.com/2962686/128996791-82e30d3d-a2f9-498d-b6b9-b8b2cffd4153.png">

**Comment by jneira** [comment]
Hi, thanks for the detailed bug report, i've observed that the error mentions haskelly, which is another haskell extension: https://marketplace.visualstudio.com/items?itemName=UCL.haskelly
Maybe it is colliding with this haskell extension? Could you uninstall it to check it?
