### ISSUE TITLE
Trying to format procs JS error

### ISSUE THREAD

**Issue by mip29** [haskell/vscode-haskell#446]
I'm using the Haskell plugin in VS Code, but I cannot seem to format my code. Whenever I try to format, nothing happens.

I'm checking some logging and I found the following error message which shows when trying to format:
```
[2021-08-29 23:18:41.687] [renderer1] [error] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at H (c:\Users\Michiel Peeters\.vscode-oss\extensions\haskell.haskell-1.6.1\dist\extension.js:247:128185)
	at c:\Users\Michiel Peeters\.vscode-oss\extensions\haskell.haskell-1.6.1\dist\extension.js:247:133572
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (c:\Users\Michiel Peeters\.vscode-oss\extensions\haskell.haskell-1.6.1\dist\extension.js:247:133565)
	at c:\Users\Michiel Peeters\.vscode-oss\extensions\haskell.haskell-1.6.1\dist\extension.js:1:48353
	at async c.provideDocumentSymbols (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:161482)
```

I've tried looking at the file in question, but it's huge and I wouldn't know where to start.

**Comment by jneira** [comment]
Hi, thanks for reporting the error, i am afraid that is was already reported in #445. I've updated that issue to mention the concrete error and make it more general (as the error is thrown trying several features including formatting)
So i am gonna close this one, you can track its eventual resolution in #445
