### ISSUE TITLE
ERROR Error: Project requires GHCup but it isn't installed (WSL2)

### ISSUE THREAD

**Issue by wclr** [haskell/vscode-haskell#903]
After updating the extension to v2.

```
2023-07-03 09:21:29.4540000 [client] INFO Finding haskell-language-server
2023-07-03 09:21:29.4720000 [client] INFO Checking for ghcup installation
2023-07-03 09:23:13.2320000 [client] ERROR Error: Project requires GHCup but it isn't installed
	at /root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:276868
	at Generator.next (<anonymous>)
	at /root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:272698
	at new Promise (<anonymous>)
	at r (/root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:272443)
	at A (/root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:276373)
	at /root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:275026
	at Generator.next (<anonymous>)
	at /root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:272698
	at new Promise (<anonymous>)
	at r (/root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:272443)
	at T (/root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:274902)
	at /root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:276304
	at Generator.next (<anonymous>)
	at /root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:272698
	at new Promise (<anonymous>)
	at r (/root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:272443)
	at _ (/root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:276082)
	at /root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:279514
	at Generator.next (<anonymous>)
	at s (/root/.vscode-server-insiders/extensions/haskell.haskell-2.2.4/dist/extension.js:1:272500)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

GHC is installed and it all worked before extensions update.
```
root@DESKTOP-PDE8C70:/code/...# ghcup --version
The GHCup Haskell installer, version 0.1.19.4
```

### Your environment

Which OS do you use:

Window 10 WSL2

**Comment by hasufell** [comment]
See https://github.com/haskell/vscode-haskell#stackcabalghc-can-not-be-found

**Comment by wclr** [comment]
Thanks, adding:
```
"haskell.serverEnvironment": {
    "PATH": "${HOME}/.ghcup/bin:$PATH"
  },
```
to settings helped.
