### ISSUE TITLE
Extension failing to find Ghcup executable,even though it is pointed at the path.

### ISSUE THREAD

**Issue by Nucl3arSn3k** [haskell/vscode-haskell#939]
### Your environment

Windows

### Steps to reproduce

Install the extension and point it towards your Ghcup executable path,which in my case is  
 C:\ghcup\bin\ghc.exe.
 

### Expected behaviour

The extension should detect the Ghcup binary

### Actual behaviour

The extension does not detect the Ghcup binary.

### Debug Information

Here's the language server debug info.

<details>
<summary>
Debug output:
</summary>

```
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-2.0.0.1.exe) Version 2.0.0.1 x86_64 ghc-9.6.2
Current directory: C:\Users\shred\Documents\GitHub\HaskellFileReader
Operating system: mingw32
Arguments: ["--debug"]
Cradle directory: C:\Users\shred\Documents\GitHub\HaskellFileReader
Cradle type: Cabal

Tool versions found on the $PATH
cabal:          3.6.2.0
stack:          2.11.1
ghc:            9.2.8


Consulting the cradle to get project GHC version...
2023-08-17T00:16:47.379999Z | Debug | executing command: cabal exec -v0 -- ghc --print-libdir
2023-08-17T00:16:49.579867Z | Debug | executing command: cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2023-08-17T00:16:50.679873Z | Debug | executing command: ghc -rtsopts=ignore -outputdir C:\Users\shred\AppData\Local\Temp\hie-bios-5227515af7f384ba -o C:\Users\shred\AppData\Local\hie-bios\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.exe C:\Users\shred\AppData\Local\hie-bios\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.hs
[1 of 1] Compiling Main             ( C:\\Users\shred\AppData\Local\hie-bios\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.hs, C:\\Users\shred\AppData\Local\Temp\hie-bios-5227515af7f384ba\Main.o )
Linking C:\\Users\\shred\\AppData\\Local\\hie-bios\\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.exe ...
2023-08-17T00:16:55.215719Z | Debug | executing command: cabal --builddir=C:\Users\shred\AppData\Local\hie-bios\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27 v2-exec --with-compiler C:\Users\shred\AppData\Local\hie-bios\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.exe --with-hc-pkg C:\ghcup\ghc\9.2.8\bin\ghc-pkg-9.2.8.exe ghc -v0 -- --numeric-version
Project GHC version: 9.2.8
haskell-language-server exe candidates: ["haskell-language-server-9.2.8.exe","haskell-language-server.exe"]
Launching haskell-language-server exe at:C:\ghcup\bin\haskell-language-server-9.2.8.exe
2023-08-17T00:16:57.322148Z | Info | No log file specified; using stderr.
2023-08-17T00:16:57.372648Z | Info | haskell-language-server version: 2.0.0.1 (GHC: 9.2.8) (PATH: C:\ghcup\bin\haskell-language-server-9.2.8~2.0.0.1.exe)
2023-08-17T00:16:57.386649Z | Info | Directory: C:\Users\shred\Documents\GitHub\HaskellFileReader
2023-08-17T00:16:57.390648Z | Info | Logging heap statistics every 60.00s
 ghcide setup tester in C:\Users\shred\Documents\GitHub\HaskellFileReader.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in C:\Users\shred\Documents\GitHub\HaskellFileReader
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE
2023-08-17T00:16:57.556149Z | Debug | Initializing exports map from hiedb
2023-08-17T00:16:57.571649Z | Debug | Shake session initialized

Step2023-08-17T00:16:57.579151Z | Debug | Done initializing exports map from hiedb. Size: 0
 4/4: Type checking the files
2023-08-17T00:16:57.596151Z | Info | Cradle path: app\Main.hs
2023-08-17T00:16:57.596651Z | Warning | No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for app\Main.hs.
Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
2023-08-17T00:16:57.661650Z | Debug | Cradle: Cradle {cradleRootDir = "C:\\Users\\shred\\Documents\\GitHub\\HaskellFileReader", cradleOptsProg = CradleAction: Cabal}
2023-08-17T00:16:57.663150Z | Info | invoking build tool to determine build flags (this may take some time depending on the cache)
2023-08-17T00:16:57.663653Z | Debug | executing command: cabal exec -v0 -- ghc --print-libdir
2023-08-17T00:16:57.825652Z | Debug | executing command: cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2023-08-17T00:16:58.389156Z | Debug | executing command: cabal --builddir=C:\Users\shred\AppData\Local\hie-bios\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27 v2-repl --with-compiler C:\Users\shred\AppData\Local\hie-bios\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.exe --with-hc-pkg C:\ghcup\ghc\9.2.8\bin\ghc-pkg-9.2.8.exe HaskellFileReader:exe:HaskellFileReader
2023-08-17T00:16:58.470654Z | Debug | Build profile: -w ghc-9.2.8 -O1
2023-08-17T00:16:58.471157Z | Debug | In order, the following will be built (use -v for more details):
2023-08-17T00:16:58.471157Z | Debug |  - HaskellFileReader-0.1.0.0 (exe:HaskellFileReader) (first run)
2023-08-17T00:16:58.553155Z | Debug | Configuring executable 'HaskellFileReader' for HaskellFileReader-0.1.0.0..
2023-08-17T00:17:04.557149Z | Debug | Preprocessing executable 'HaskellFileReader' for HaskellFileReader-0.1.0.0..
2023-08-17T00:17:04.597650Z | Debug | executing command: cabal exec -v0 -- ghc --print-libdir
2023-08-17T00:17:04.740141Z | Debug | executing command: cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)
2023-08-17T00:17:05.118232Z | Debug | executing command: cabal --builddir=C:\Users\shred\AppData\Local\hie-bios\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27 v2-exec --with-compiler C:\Users\shred\AppData\Local\hie-bios\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.exe --with-hc-pkg C:\ghcup\ghc\9.2.8\bin\ghc-pkg-9.2.8.exe ghc -v0 -- --print-libdir
2023-08-17T00:17:05.419234Z | Debug | Session loading result: Right (ComponentOptions {componentOptions = ["-fbuilding-cabal-package","-O0","-outputdir","C:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\HaskellFileReader-tmp","-odir","C:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\HaskellFileReader-tmp","-hidir","C:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\HaskellFileReader-tmp","-stubdir","C:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\HaskellFileReader-tmp","-i","-iC:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\HaskellFileReader-tmp","-iapp","-iC:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\autogen","-iC:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\global-autogen","-IC:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\autogen","-IC:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\global-autogen","-IC:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\HaskellFileReader-tmp","-IC:\\msys64\\mingw64\\include","-optP-include","-optPC:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\build\\HaskellFileReader\\autogen\\cabal_macros.h","-LC:\\msys64\\mingw64\\lib","-hide-all-packages","-Wmissing-home-modules","-no-user-package-db","-package-db","C:\\cabal\\store\\ghc-9.2.8\\package.db","-package-db","C:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\packagedb\\ghc-9.2.8","-package-db","C:\\Users\\shred\\AppData\\Local\\hie-bios\\dist-HaskellFileReader-395fea6b49784a609be6accd766b9b27\\build\\x86_64-windows\\ghc-9.2.8\\HaskellFileReader-0.1.0.0\\x\\HaskellFileReader\\package.conf.inplace","-package-id","base-4.16.4.0","-XHaskell2010","app\\Main.hs","-Wall","-hide-all-packages"], componentRoot = "C:\\Users\\shred\\Documents\\GitHub\\HaskellFileReader", componentDependencies = ["HaskellFileReader.cabal","cabal.project","cabal.project.local"]},"C:\\ghcup\\ghc\\9.2.8\\lib")
2023-08-17T00:17:05.484234Z | Info | Interface files cache directory: C:\Users\shred\AppData\Local\ghcide\main-2677251800283f3d366ec030b0423c67c1db5ccf
2023-08-17T00:17:05.485233Z | Info | Making new HscEnv. In-place unit ids: [main]
2023-08-17T00:17:05.501233Z | Debug | New component cache HscEnvEq: (([],Just HscEnvEq 4),fromList [("HaskellFileReader.cabal",Just 2023-08-16 23:44:42.0828354 UTC),("cabal.project",Nothing),("cabal.project.local",Nothing)])2023-08-17T00:17:05.501734Z | Debug | Known files updated:
  fromList [(TargetFile NormalizedFilePath "C:\\Users\\shred\\Documents\\GitHub\\HaskellFileReader\\app\\Main.hs",fromList ["C:\\Users\\shred\\Documents\\GitHub\\HaskellFileReader\\app\\Main.hs"])]
2023-08-17T00:17:05.502234Z | Debug | Finished build session
AsyncCancelled
2023-08-17T00:17:05.502234Z | Debug | Restarting build session due to new component
Action Queue: [User TypeCheck]
Keys: [GhcSessionIO; , GetKnownTargets; ]
Aborting previous build session took 0.00s
2023-08-17T00:17:05.503735Z | Debug | hlint: Getting hlint ideas for  NormalizedFilePath "C:\\Users\\shred\\Documents\\GitHub\\HaskellFileReader\\app\\Main.hs"
2023-08-17T00:17:05.733235Z | Debug | hlint: Using extensions for  NormalizedFilePath "C:\\Users\\shred\\Documents\\GitHub\\HaskellFileReader\\app\\Main.hs": [ MonomorphismRestriction
                                                                                                                         , DeepSubsumption
                                                                                                                         , RelaxedPolyRec
                                                                                                                         , ForeignFunctionInterface
                                                                                                                         , ImplicitPrelude
                                                                                                                         , DoAndIfThenElse
                                                                                                                         , EmptyDataDecls
                                                                                                                         , PatternGuards
                                                                                                                         , DatatypeContexts
                                                                                                                         , TraditionalRecordSyntax
                                                                                                                         , StarIsType
                                                                                                                         , CUSKs
                                                                                                                         , FieldSelectors ]
2023-08-17T00:17:05.760738Z | Debug | Finished: User TypeCheck Took: 0.26s
2023-08-17T00:17:05.768717Z | Debug | Finished: GetHie Took: 0.01s

2023-08-17T00:17:05.768717Z | Debug | Finished: GenerateCore Took: 0.00s
Completed (1 file worked, 0 files failed)
```

</details>

Here's the extension specific log.

<details>
<summary>
Extension log:
</summary>

```
2023-08-17 00:06:13.6700000 [client] INFO Finding haskell-language-server
2023-08-17 00:06:13.6700000 [client] INFO Checking for ghcup installation
2023-08-17 00:06:13.6700000 [client] INFO Trying to find the ghcup executable in:  C:\ghcup\bin\ghc.exe
2023-08-17 00:06:13.7160000 [client] ERROR Internal Error: Could not find a ghcup binary at  C:\ghcup\bin\ghc.exe!
2023-08-17 00:06:13.7170000 [client] ERROR Error: Could not find a ghcup binary at  C:\ghcup\bin\ghc.exe!
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:53367
	at Generator.next (<anonymous>)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49343
	at new Promise (<anonymous>)
	at r (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49088)
	at w (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:53018)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:51671
	at Generator.next (<anonymous>)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49343
	at new Promise (<anonymous>)
	at r (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49088)
	at v (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:51547)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:52949
	at Generator.next (<anonymous>)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49343
	at new Promise (<anonymous>)
	at r (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49088)
	at C (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:52727)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:56159
	at Generator.next (<anonymous>)
	at s (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49145)
```

</details>

**Comment by fendor** [comment]
Hi, thank you for your bug report!

You supplied the path to Ghc, not ghcup: `C:\ghcup\bin\ghc.exe` /= `C:\ghcup\bin\ghcup.exe`

**Comment by Nucl3arSn3k** [comment]
I fixed the path and it's still giving me the same error.
<details>

<summary>Extension logs here</summary>

```2023-08-17 21:29:03.6120000 [client] INFO Finding haskell-language-server
2023-08-17 21:29:03.6120000 [client] INFO Checking for ghcup installation
2023-08-17 21:29:03.6120000 [client] INFO Trying to find the ghcup executable in:  C:\ghcup\bin\ghcup.exe
2023-08-17 21:29:03.6440000 [client] ERROR Internal Error: Could not find a ghcup binary at  C:\ghcup\bin\ghcup.exe!
2023-08-17 21:29:03.6440000 [client] ERROR Error: Could not find a ghcup binary at  C:\ghcup\bin\ghcup.exe!
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:53367
	at Generator.next (<anonymous>)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49343
	at new Promise (<anonymous>)
	at r (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49088)
	at w (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:53018)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:51671
	at Generator.next (<anonymous>)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49343
	at new Promise (<anonymous>)
	at r (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49088)
	at v (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:51547)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:52949
	at Generator.next (<anonymous>)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49343
	at new Promise (<anonymous>)
	at r (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49088)
	at C (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:52727)
	at c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:56159
	at Generator.next (<anonymous>)
	at s (c:\Users\shred\.vscode\extensions\haskell.haskell-2.4.1\dist\extension.js:1:49145)
```
</details>

**Comment by fendor** [comment]
And the path exists? `whereis ghcup` or something like that yields that path, and you can run `C:\ghcup\bin\ghcup.exe --help`?

Perhaps your ghcup installation is borked, did you try reinstalling?

**Comment by tomasaschan** [comment]
I can reproduce this, but with a slightly different env setup. I run VS Code on Windows against WSL, so the extension is effectively running under Linux. I got this error message on startup, did not have any value set for `haskell.ghcupExecutablePath`, but `ghcup` is in my `$PATH`. So I did `which ghcup` to find it at `/home/tomas/.ghcup/bin/ghcup`, changed the setting to this value and reloaded the window - and  I still got the error!

<img width="1041" alt="image" src="https://github.com/haskell/vscode-haskell/assets/1550920/2530dee2-c18b-4bac-98d6-460a6cc967e6">

I can also verify that running e.g. `ghcup list` from the terminal gives the expected output (and shows that recommended versions are installed for all of `ghc`, `cabal`, `hls`, `stack` and `gchup`).

Anything else I can do to help troubleshoot?

**Comment by fendor** [comment]
You have a typo in the path, `.gchup` /= `.ghcup`. Can you try again with the path fixed?

**Comment by BogdanSvirsky** [comment]
Has anyone managed to solve this issue?

**Comment by fendor** [comment]
@BogdanSvirsky So far, none of the reports here actually uncovered a bug but always a typo in the provided path to ghcup. Please provide some logs for your issue or explain what you are trying to do.

**Comment by fendor** [comment]
Closing as non reproducible
